export default {
  "LOGIN_CAP": "LOGIN",
  "ANSWER": "Answer",
  "LOGIN": "Login",
  "SIGNUP": "Sign Up",
  "STREAMLINE_PROCESS": "Streamline Processes And Optimize Resource Use.",
  "LOGIN_WITH_GOOGLE": "Login with Google",
  "LOGIN_WITH_APPLE": "Login with Apple",
  "GUEST_LOGIN": "Guest User Login (Demo Mode)",
  "WELCOME": "Welcome,",
  "QUESTION_BANK": "Question Bank",
  "20K_ACTIVE_LEARNERS": "20,000 + Active Learners",
  "STUDY_MODE": "Study Mode",
  "PRACTICE_MODE": "Practice Mode",
  "EXAM_MODE": "Exam Mode",
  "TEST_YOUR_BEST": "Test Your Best",
  "START_TEST": "Start Test",
  "START_EXAM": "Start Exam",
  'SAVED_TESTS': "Saved Tests",
  'REPORTS': "Reports",
  'SAVED_QUESTIONS': "Saved Questions",
  'SETTINGS': "Settings",
  'STUDY_PLANNER': "Study Planner",
  'GET_PREMIUM': "Get Premium",
  'STUDY_MATERIAL': "Study Material",
  "SELECT_SUBJECT": "Select Subject",
  "MORE_TOPICS": "More Topics",
  "SELECTED_TOPICS": "Selected Topics",
  "HARD": "Hard",
  "NORMAL": "Normal",
  "EASY": "Easy",
  "SELECT_DIFFICULTY_LEVEL": "Select Difficulty Level",
  "SELECT_ALL": "Select all",
  "MORE_ABOUT_THIS_SUBJECT": "More about this subject",
  "START_STUDY": "Start Study",
  "REPORT_QUESTION": "Report Question",
  "FLAG_QUESTION": "Flag Question",
  "CHECK_EXPLANATION": "Check Explanation",
  "FINISH_STUDY": "Finish Study",
  "KEEP_UP_BRING_CLOSER": "Keep It Up — Every Session Gets You Closer To Your Goals!",
  "MINUTES": "Minutes",
  "TIME_INVESTED": "Time invested",
  "EXIT_STUDY_MODE": "Exit Study Mode",
  "EXIT_STUDY_MODE?": "Exit Study Mode?",
  "YOUR_PROGRESS_SONT_SAVE": "Your progress won’t be saved unless you upgrade to premium.",
  "UPGRADE_AND_SAVE": "Upgrade & Save",
  "EXIT_WITHOUT_SAVING": "Exit Without Saving",
  "SAVE": "Save",
  "EXIT": "Exit",
  "EXPLANATION": "Explanation",
  "QUESTIONCOLON": "Question:",
  "SELECT_EXPLANATION_OPTION": "Select explanation type",
  "EXPLANATION_BY_VIDEO": "Explain by Video",
  "EXPLANATION_BY_THEORY": "Explain by Theory",
  "VIEW_EXPLANATION": "View Explanation",
  "RESUME": "Resume",
  "VIDEO_EXPLANATION": "Video Explanation",
  "START_PRACTICE": "Start Practice",
  "FINISH_PRACTICE": "Finish Practice",
  "FINISH_EXAM": "Finish Exam",
  "EXIT_PRACTICE": "Exit Practice",
  "QUESTIONS": "Questions",
  "EXAM_RESULTS": "Exam Results",
  "EXAM_OVERVIEW": "Exam Overview",
  "ANSWER_SUMMARY": "Answer Summary",
  "SEND_REPORT": "Send Report",
  "SELECT_ISSUE_TO_REPORT": "Select issue to report",
  "SELECT_TYPE_OF_EXPLANATION": "Select Type of Explanation",
  "THEORY": "Theory",
  "MY_REPORTS": "My Reports",
  "FILTER": "Filter",
  "SORT": "Sort",
  "YOUR_RECENT_REPORT": "Your Recent Reports",
  "GOALS": "Goals",
  "NO_RECENT_REMINDERS_FOUND": "No Recent Reminders Found",
  "NO_UPCOMING_GOALS_FOUND": "No Upcoming Goals Found",
  "NO_RECORD_FOUND": "No Record Found",
  "TODAY": "Today",
  "YESTERDAY": "Yesterday",
  "TOMORROW": "Tomorrow",
  "AT": "at",
  "UPCOMING": "Upcoming",
  "RECENT_REMINDERS": "Recent Reminders",
  "ADD_GOAL": "Add Goal",
  "CREATE_A_NEW_GOAL": "Create a New Goal",
  "CREATE_GOAL": "Create Goal",
  "GOAL_TITLE": "Goal Title",
  "EG_FINAL_EXAM": "Eg. Final Exam",
  "DATE": "Date",
  "SELECT_DATE": "Select Date",
  "TIME": "Time",
  "SELECT_TIME": "Select Time",
  "THIS_IS_REQUIRED": "This is required",
  "NEW_GOAL_CREATED_SUCCESS": "New Goal Created Successfully",
  "APP_SETTINGS": "App Settings",
  "PREFERENCES": "Preferences",
  "REGION": "Region",
  "LICENSE": "License",
  "lICENSE": "license",
  "PERSONAL_DETAILS": "Personal Details",
  "OFFLINE_ACCESS": "Offline Access",
  "FAQs": "FAQ's",
  "TUTORIALS_AND_GUIDES": "Tutorials and Guides",
  "ABOUT_APP": "About App",
  "TAKE_YOUR_VIDEOS_TO_NEXT_LEVEL": "Take your videos to next level with more features.",
  "EXPIRE_IN": "Expire in",
  "UPGRADE_PLAN": "Upgrade Plan",
  "PER_MONTH": "/ month",
  "DAYS": "Days",
  "PREMIUM": "Premium",
  "SELECT_REGION": "Select Region",
  "SELECT_QUESTION_BANK": "Select Question Bank",
  "SELECT_LICENSE": "Select license",
  "QUESTION_PREFERENCES": "Question Preferences",
  "GO_TO_NEXT_QUESTION_AUTO": "Go to next question automatically",
  "CONFIRM_ANSWER_SELECTION": "Confirm Answer Selection",
  "SEQUENTIAL_QUESTION_ORDER": "Sequential Question Order",
  "GO_TO_NEXT_QUESTION_AUTOMATICALLY": "Go to next question automatically",
  "USERNAME": "Username",
  "ENTER_USERNAME": "Enter your name",
  "ENTER_YOUR_EMAIL": "Enter your email",
  "LOGIN_TIME": "Login time",
  "EMAIL": "Email",
  "QUESTION_BANK_VERSION (QBV)": "Question Bank Version (QBV)",
  "LANGUAGE": "Language",
  "DARK_MODE": "Dark Mode",
  "TERMS_AND_CONDITION": "Terms & Conditions",
  "ENGLISH": "English",
  "FOLLOW_SYSTEM": "Follow System",
  "FREQUENTLY_ASKED_QUESTIONS": "Frequently Asked Questions",
  "LEARN_MORE": "Learn More",
  "HOW_TO_USE_FPP": "How to use FPP",
  "RULES_FOR_FPP": "Rules for FPP",
  "WHAT_IS_RBX_CALCULATOR": "What is RBX Calculator",
  "HOW_TO_USE_PROMO": "How to use promo code",
  "TUTORIALS": "Tutorials",
  "UPGRADE_TO_PRO_MEMBERSHIP": "Upgrade to Pro Membership",
  "GET_ALL_ACCESS_EXTRA_20_PERCENT_SUBSCRIBE_ANUALLY": "Get all access and an extra 20% off when you subscribe annually",
  "UPGRADE_TO_PLUS": "Upgrade to plus",
  "BEST_CHOICE_FOR_INDIVIDUALS": "Best Choice for Individuals",
  "ACTIVATION_CODE": "Activation Code",
  "ENTER_CODE": "Enter Code",
  "ENTER_CODE_TO_DISCOUNT": "Enter Code to Get Discount",
  "SUBSCRIPTIONS": "Subscriptions",
  "MY_QUESTIONS": "My Questions",
  "SHOWING_QUESTIONS": "Showing Questions",
  "EUROPE": "Europe",
  "STUDY": "Study",
  "PRACTICE": "Practice",
  "EXAM": "Exam",
  "FONT_SIZE": "Font Size",
  "SELECT_MODE": "Select Mode",
  "SHOW_REPORTS": "Show Reports",
  "GOOGLE_LOGIN_SUCCESS": "Google Login Successfully",
  "USER_CANCELLED_LOGIN": "Error, User Cancelled the login",
  "GUEST": "Guest",
  "GUEST_USER": "Guest User",
  "SIGNIN": "Sign In",
  "SIGNIN_TO_SAVE_PROGRESS": "Sign In to save progress",
  "LOGOUT": "Logout",
  "DELETE_ACCOUNT": "Delete Account",
  "SIGNIN_OR_CREATE_ACCOUNT": "Sign in or Create Account",
  "VIDEO": "Video"
};
